name: Package and Upload to S3

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  package-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: Yalab7/WordPress
    
    - name: Upload to S3
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create Tar File
      run: |
        cd ..
        date=$(date +'%Y-%m-%d_%H-%M-%S')
        tar -czvf app_$date.tar.gz WordPress/
        aws s3 cp app_$date.tar.gz s3://atef-wp-app/
        aws s3 cp app_$date.tar.gz s3://atef-wp-app/latest.tar.gz
